- name: Mount data volume
  hosts: k3s_master
  become: true
  tasks:
    - name: Check if volume is formatted
      command: blkid "{{ lookup('env', 'DATA_VOLUME_DEVICE') }}"
      register: blkid_check
      failed_when: false
      changed_when: false

    - name: Create mount point
      file:
        path: /mnt/data
        state: directory

    - name: Mount volume
      mount:
        path: /mnt/data
        src: "{{ lookup('env', 'DATA_VOLUME_DEVICE') }}"
        fstype: ext4
        state: mounted